apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-configmap
  namespace: logging
data:
  elasticsearch.yml: |
    network.host: 0.0.0.0
    xpack.license.self_generated.type: basic
    xpack.security.enabled: true
    xpack.monitoring.collection.enabled: true