apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: logging
  labels:
    app: elasticsearch
spec:
  ports:
    - port: 9200
      name: tcp
    - port: 9300
      name: server
  clusterIP: None
  selector:
    app: elasticsearch
