apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: logging
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    xpack.monitoring.elasticsearch.hosts: "http://elasticsearch:9200"
    xpack.monitoring.elasticsearch.username: elastic
    xpack.monitoring.elasticsearch.password: admin
    xpack.monitoring.enabled: true
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    # all input will come from filebeat, no local logs
    input {
      beats{
        port => 5044
      }
      udp{
        port => 5000
        type => syslog
        codec => json
        }
      tcp{
        port => 5000
        type => syslog
        codec => json_lines
      }
      http{
        port => 5001
        codec => json
      }
    }
    output{
      elasticsearch{
        hosts => ["http://elasticsearch:9200"]
        ecs_compatibility => disabled
        user => "elastic"
        password => "admin"
        index => "shorturl-%{+YYYY.MM.dd}"
      }
    }
