apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-11-03T10:25:42Z"
  name: irsa-test-pod
  namespace: default
  resourceVersion: "864461"
  uid: bd1e1112-113b-4732-8e86-616fa664dc41
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: test-container
    resources:
      limits:
        cpu: "2" #1500m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-q5fdb
      readOnly: true
  