apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: logging
  labels:
    app: logging
spec:
  ports:
    - name: tcp
      port: 5601
      targetPort: 5601
  selector:
    app: kibana
