apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.23.0
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    "global":
      "resolve_timeout": "5m"
      "smtp_smarthost": "xxx"
      "smtp_from": "xxx
      "smtp_auth_username": "xxx"
      "smtp_auth_password": "xxxx"
      "smtp_require_tls": true
    "inhibit_rules":
    - "equal":
      - "namespace"
      - "alertname"
      "source_matchers":
      - "severity = critical"
      "target_matchers":
      - "severity =~ warning|info"
    - "equal":
      - "namespace"
      - "alertname"
      "source_matchers":
      - "severity = warning"
      "target_matchers":
      - "severity = info"
    "receivers":
    - "name": "mail"
      "email_configs":
          - "to": "xxxx"
    - "name": "teams"
      "webhook_configs":
          - "url": "http://prom2teams.default.svc.cluster.local:8089"
            "send_resolved": true
    "route":
      "group_by":
          - "alertname"
      "group_interval": "5m"
      "group_wait": "30s"
      "receiver": "teams"

      "repeat_interval": "10m"
      "routes":
      - "matchers":
        - "severity = critical"
        - "severity = warning"
        "receiver": "mail"
      - "matchers":
        - "severity = critical"
        - "severity = warning"
        "receiver": "teams"
#      - "matchers":
#        - "severity = critical"
#        "receiver": "mail"
type: Opaque