apiVersion: v1
kind: LimitRange
metadata:
  name: pvc-limits
  namespace: logging
spec:
  limits:
    - type: PersistentVolumeClaim
      max:
        storage: "20Gi"
      min:
        storage: "1Gi"
