apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: externalsecrets.external-secrets.io
spec:
  group: external-secrets.io
  names:
    kind: ExternalSecret
    listKind: ExternalSecretList
    plural: externalsecrets
    singular: externalsecret
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                secretStoreRef:
                  type: object
                  properties:
                    name:
                      type: string
                    kind:
                      type: string
                      enum:
                        - SecretStore
                        - ClusterSecretStore
                target:
                  type: object
                  properties:
                    name:
                      type: string
                    creationPolicy:
                      type: string
                data:
                  type: array
                  items:
                    type: object
                    properties:
                      secretKey:
                        type: string
                      remoteRef:
                        type: object
                        properties:
                          key:
                            type: string
                          property:
                            type: string
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: secretstores.external-secrets.io
spec:
  group: external-secrets.io
  names:
    kind: SecretStore
    listKind: SecretStoreList
    plural: secretstores
    singular: secretstore
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                provider:
                  type: object
                  properties:
                    aws:
                      type: object
                      properties:
                        service:
                          type: string
                        region:
                          type: string
                        auth:
                          type: object
                          properties:
                            secretRef:
                              type: object
                              properties:
                                accessKeyID:
                                  type: object
                                  properties:
                                    name:
                                      type: string
                                    key:
                                      type: string
                                secretAccessKey:
                                  type: object
                                  properties:
                                    name:
                                      type: string
                                    key:
                                      type: string
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clustersecretstores.external-secrets.io
spec:
  group: external-secrets.io
  names:
    kind: ClusterSecretStore
    listKind: ClusterSecretStoreList
    plural: clustersecretstores
    singular: clustersecretstore
  scope: Cluster
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                provider:
                  type: object
                  properties:
                    aws:
                      type: object
                      properties:
                        service:
                          type: string
                        region:
                          type: string
                        auth:
                          type: object
                          properties:
                            secretRef:
                              type: object
                              properties:
                                accessKeyID:
                                  type: object
                                  properties:
                                    name:
                                      type: string
                                    key:
                                      type: string
                                secretAccessKey:
                                  type: object
                                  properties:
                                    name:
                                      type: string
                                    key:
                                      type: string
