# kustomize/base/external-secret.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-secret
  namespace: shorturl
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: prod/db/postgres   # Replace with your secret name
        property: username
    - secretKey: password
      remoteRef:
        key: prod/db/postgres   # Replace with your secret name
        property: password
    - secretKey: SESSION_SECRET
      remoteRef:
        key: prod/googleOauth   # Replace with your secret name
        property: SESSION_SECRET
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: prod/googleOauth   # Replace with your secret name
        property: GOOGLE_CLIENT_ID
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: prod/googleOauth   # Replace with your secret name
        property: GOOGLE_CLIENT_SECRET
