apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: external-secrets-operator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-secrets-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: external-secrets-operator
    spec:
      containers:
      - args:
        - --metrics-addr=:8080
        - --enable-leader-election
        image: ghcr.io/external-secrets/external-secrets:v0.10.5
        imagePullPolicy: IfNotPresent
        name: manager
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: external-secrets-sa
      serviceAccountName: external-secrets-sa
      terminationGracePeriodSeconds: 30