# Service Account for External Secrets Operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::848417356303:role/my-eks-service-account-role
---
# ClusterRole for permissions to manage secrets and access AWS secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-cluster-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - update
  - apiGroups:
      - external-secrets.io
    resources:
      - "*"
    verbs:
      - "*"
---
# ClusterRoleBinding to bind the ServiceAccount to the ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secrets-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-secrets-cluster-role
subjects:
  - kind: ServiceAccount
    name: external-secrets-sa
    namespace: kube-system