apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sa-list-permissions
rules:
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sa-list-binding
subjects:
- kind: ServiceAccount
  name: external-secrets-sa
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: sa-list-permissions
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-clusterrole
rules:
- apiGroups: [""]
  resources: ["secrets", "serviceaccounts", "namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["external-secrets.io"]
  resources: ["externalsecrets", "secretstores"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secrets-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: external-secrets-sa
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: external-secrets-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-secrets-token-creator
  namespace: shorturl
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets-token-creator-binding
  namespace: shorturl
subjects:
  - kind: ServiceAccount
    name: external-secrets-sa
    namespace: kube-system
roleRef:
  kind: Role
  name: external-secrets-token-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-secrets-token-creator
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["serviceaccounts/token"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets-token-creator-binding
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: external-secrets-sa
  namespace: kube-system
roleRef:
  kind: Role
  name: external-secrets-token-creator
  apiGroup: rbac.authorization.k8s.io


