apiVersion: v1
kind: LimitRange
metadata:
  name: shorturl-limits
  namespace: shorturl
spec:
  limits:
    - default:
        memory: "1Gi"
      defaultRequest:
        cpu: "250m"
        memory: "512Mi"
      type: Container
# ---
# apiVersion: v1
# kind: LimitRange
# metadata:
#   name: shorturl-limits
#   namespace: shorturl
# spec:
#   limits:
#     - type: Pod
#       max:
#         memory: "4Gi"
#       min:
#         cpu: "500m"
#         memory: "1Gi"


