apiVersion: v1
kind: Service
metadata:
  name: postgres  
  namespace: shorturl  
spec:
  type: ExternalName
  externalName: shorturl-db-instance.cmzoy0kkfqoc.us-east-1.rds.amazonaws.com
  ports:
    - port: 5432  
      targetPort: 5432  
      protocol: TCP
